set(ARCHCFLAGS          "-Wstrict-prototypes -Wno-attributes -Wno-unknown-pragmas -Wno-psabi")
set(ARCHCPUFLAGS        "-mlittle-endian -march=armv7e-m -mtune=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -Wa,-mthumb -Wa,-mimplicit-it=always")
set(ARCHCXXFLAGS        "-Wno-attributes -Wno-unknown-pragmas -Wno-psabi -std=gnu++17")
set(ARCHPICFLAGS        "-fpic -msingle-pic-base -mpic-register=r10")
set(ARCHWARNINGS        "")
set(ARCHWARNINGSXX      "")
set(ARCHOPTIMIZATION    "-fomit-frame-pointer --param=min-pagesize=0 -fno-common -Wall -Wshadow -Wundef -ffunction-sections -fdata-sections -g")
set(CROSSDEV            "arm-none-eabi-")
set(CMAKE_C_COMPILER    "arm-none-eabi-gcc")
set(CMAKE_CXX_COMPILER  "arm-none-eabi-g++")
set(CMAKE_LINKER        "arm-none-eabi-ld")
set(CMAKE_OBJCOPY       "arm-none-eabi-objcopy")
set(CMAKE_OBJDUMP       "arm-none-eabi-objdump")
set(NXFLATLDFLAGS1      "-r -d -warn-common")
set(NXFLATLDFLAGS2      "-r -d -warn-common -T/home/sergey/DEV/DEV/DRONES/nuttx-git/nuttx/binfmt/libnxflat/gnu-nxflat-pcrel.ld -no-check-sections")
set(OBJEXT              ".o")
set(LIBEXT              ".a")
set(EXEEXT              "")
set(HOSTCC              "cc")
set(HOSTINCLUDES        "")
set(HOSTCFLAGS          "-O2 -Wall -Wstrict-prototypes -Wshadow -DHAVE_STRTOK_C=1 -DHAVE_STRNDUP=1")
set(HOSTLDFLAGS         "")
set(HOSTEXEEXT          "")
set(LDNAME              "flash.ld")
set(LDELFFLAGS          "-r /home/sergey/DEV/DEV/DRONES/nuttx-git/nuttx/arch/arm/src/crt0.o -e __start ")
set(LDMODULEFLAGS       "-r")
set(NUTTX_ARCH          "arm")
set(NUTTX_ARCH_CHIP     "stm32h7")
set(NUTTX_BOARD         "nucleo-h743zi")
set(NUTTX_BUILD         "flat")
set(NUTTX_CXX           "cxx")
set(LLVM_ARCHTYPE       "thumbv7em")
set(LLVM_CPUTYPE        "cortex-m7")
set(LLVM_ABITYPE        "eabihf")
set(EXTRA_LIBS       "/opt/st/stm32cubeclt_1.16.0/GNU-tools-for-STM32/bin/../lib/gcc/arm-none-eabi/12.3.1/thumb/v7e-m+dp/hard/libgcc.a /opt/st/stm32cubeclt_1.16.0/GNU-tools-for-STM32/bin/../lib/gcc/arm-none-eabi/12.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+dp/hard/libm.a /opt/st/stm32cubeclt_1.16.0/GNU-tools-for-STM32/bin/../lib/gcc/arm-none-eabi/12.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+dp/hard/libsupc++.a /opt/st/stm32cubeclt_1.16.0/GNU-tools-for-STM32/bin/../lib/gcc/arm-none-eabi/12.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+dp/hard/libstdc++.a")
set(EXTRA_OBJS       "")
set(HEAD_OBJ         "")
set(LDENDGROUP       "")
set(LDFLAGS          "--print-memory-usage --entry=__start -nostdlib --gc-sections --cref -Map=/home/sergey/DEV/DEV/DRONES/nuttx-git/nuttx/nuttx.map")
set(LDSTARTGROUP     "")
set(LDLIBS     "-lsched -ldrivers -lboards -lc -lmm -larch -lxx -lapps -lfs -lbinfmt -lboard ")
