#ifndef SNOW_ROTOR_CONFIG_H
#define SNOW_ROTOR_CONFIG_H

#define CONFIG_SNOW_ROTOR_CAN_DAEMON_PRIORITY 100
#define CONFIG_SNOW_ROTOR_CAN_DAEMON_STACKSIZE 1024
#define CONFIG_SNOW_ROTOR_CAN_BUFFER 1024

#define ROTOR_TASK_PRIORITY 100
#define ROTOR_TASK_STACK_SIZE 4096

#define ROTOR_CAN_TASK_PRIORITY 50
#define ROTOR_CAN_TASK_STACK_SIZE 4096

#define PREFERRED_NODE_ID 65
#define ROTOR_DEBUG 1

#define CONFIG_DEBUG_ROTOR_INFO 1
#define CONFIG_DEBUG_ROTOR_DEBUG 1
#define CONFIG_DEBUG_ROTOR_ERROR 1

#define ROTOR_CAN_NODE_ID 22
#define CANARD_ENABLE_ASSERTS 1
#define CANARD_ENABLE_CANFD 0

#endif //SNOW_ROTOR_CONFIG_H