#ifndef SNOW_ROTOR_CONFIG_H
#define SNOW_ROTOR_CONFIG_H

#define CONFIG_SNOW_ROTOR_CAN_DAEMON_PRIORITY = 100
#define CONFIG_SNOW_ROTOR_CAN_DAEMON_STACKSIZE = 1024
#define CONFIG_SNOW_ROTOR_CAN_BUFFER = 1024;

#endif //SNOW_ROTOR_CONFIG_H