#ifndef SNOW_ROTOR_CONFIG_H
#define SNOW_ROTOR_CONFIG_H

#define ROTOR_TASK_PRIORITY 100
#define ROTOR_TASK_STACK_SIZE 8192

#define ROTOR_CAN_TASK_PRIORITY 248
#define ROTOR_CAN_TASK_STACK_SIZE 8192

#define PREFERRED_NODE_ID 65
#define ROTOR_DEBUG 1

#define CONFIG_DEBUG_ROTOR_INFO 1
#define CONFIG_DEBUG_ROTOR_DEBUG 0
#define CONFIG_DEBUG_ROTOR_ERROR 1

#define ROTOR_CAN_NODE_ID 22
#define CANARD_ENABLE_ASSERTS 1
#define CANARD_ENABLE_CANFD 0

#define ROTOR_TEST_MODE 0

#endif //SNOW_ROTOR_CONFIG_H