#ifndef HOLDER_CONFIG_H
#define HOLDER_CONFIG_H

//#define CONFIG_DEV_GPIO 1
//#define CONFIG_DEV_GPIO_NSIGNALS 1

#define HOLDER_DEBUG 1
#define HOLDER_TASK_PRIORITY 90
#define HOLDER_TASK_STACK_SIZE 2048
#endif //HOLDER_CONFIG_H